# Generated by Django 6.0.6 on 2026-06-13 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7)),
                ('plan_sales', models.BigIntegerField(default=0)),
                ('plan_leads', models.IntegerField(default=0)),
                ('work_days', models.IntegerField(default=26)),
                ('passed_days', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'План месяца',
                'verbose_name_plural': 'Планы месяцев',
                'ordering': ['-month'],
            },
        ),
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('date', models.DateField(blank=True, null=True)),
                ('sales', models.BigIntegerField(default=0)),
                ('leads', models.IntegerField(default=0)),
                ('deals', models.IntegerField(default=0)),
                ('spend', models.BigIntegerField(default=0)),
                ('comment', models.TextField(blank=True, default='')),
                ('month_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_records', to='dashboard_app.monthplan')),
            ],
            options={
                'verbose_name': 'Дневная запись',
                'verbose_name_plural': 'Дневные записи',
                'ordering': ['day_number'],
            },
        ),
    ]
